name: "Container for Deploy/Redeploy Preview links"
on:
  pull_request:
    types:
      - closed

jobs:
  if-merged-with-close:
    name: "PR merged and closed"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Hello"
        run: |
          echo The PR was merged and closed
